name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the build
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU for multi-platform builds (optional)
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Buildx (optional)
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/your-image-name:${{ github.sha }} \
            --tag ghcr.io/${{ github.repository_owner }}/your-image-name:${{ github.ref_name }}

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/your-image-name:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/your-image-name:${{ github.ref_name }}
